### ISSUE TITLE
Hiding Unwanted information and adding Custom information

### ISSUE THREAD

**Issue by Tanjamuse** [TomNCatz/obsidian-gallery#14]
First of all, thank you for a revival of a very useful plugin.

I have tried adding Palette to the default hidden info, but after I've pressed save it seems to disappear again, and the palette is still there whenever I open an image. Have I done something wrong or is this a bug?

And if I've misunderstood something, then I would love the option for hiding unwanted information. Perhaps in a list with checkboxes in the settings for the gallery?

Also have you considered letting people add searchable information like we can add columns to a database?

Thanks in advance

**Comment by TomNCatz** [comment]
Alright, I think I figured out a fix for this over my lunch break and it should be in for the next release

**Comment by Tanjamuse** [comment]
Thank you so much for all your hard work.
