### ISSUE TITLE
[FR] Add tags to images anywhere

### ISSUE THREAD

**Issue by wwjCMP** [TomNCatz/obsidian-gallery#15]
Hi, TomNCatz. I hope to be able to add tags to images directly in markdown files. This will be more comfortable.

Now, it should only be possible to add tags to images in the gallery or in the meta files of the images. I believe this is not in line with the usual practice. This is because the tags for images often depend not only on the information contained in the image but also on the context in which it is placed. For example, in an article about astronomy, images often require additional tags related to astronomy as a profession. Furthermore, managing tags in a gallery is generally done after the fact, and it is not as intuitive and effective as real-time management. Therefore, I hope to make it easy to add tags to images embedded in Markdown. The gallery should serve more as a tool for image retrieval and maintenance.

**Comment by TomNCatz** [comment]
I think I have a reasonable fix for this coming out in a few minutes. In 1.1.1 if you right click on a supported embed it should open the meta leaf to the right and you can access and edit info there.

**Comment by wwjCMP** [comment]
I have to open gallery to use this method.  Is this the original intention of the design?

**Comment by TomNCatz** [comment]
I version 1.1.1 you should be able to right click on an embedded image or video anywhere in your vault and it should open the side panel to that image's meta file. If it has no meta file it should create one. It currently has a bug I am working on for images with spaces in their path, which I hope to get a fix out for today.

None of that should require you to open the gallery though, just the side panel, and then you should be able to add and remove tags in the side panel.

**Comment by wwjCMP** [comment]
![Snipaste_2023-09-24_07-28-31](https://github.com/TomNCatz/obsidian-gallery/assets/32979859/3b2e6c0f-3a68-4418-9eb3-adfabb7bfbe8)
.If I haven't opened the gallery, the error mentioned above will appear when right-clicking. After opening the gallery, it can be used normally.
