### ISSUE TITLE
[FR] Add ability to sort images in the gallery by date, filename etc.

### ISSUE THREAD

**Issue by FeralFlora** [TomNCatz/obsidian-gallery#17]
Sometimes, I go to the gallery to find an image that I'm looking for. For example, let's say I copy-pasted an image into a note, and don't know the filename. If I could sort by date, then I could easily find the image I just added. As is, I have to either search, which doesn't help that much when you are unsure of the note name, or scroll.

If this is already possible, and I've overlooked it, I apologize.

**Comment by TomNCatz** [comment]
This is a solid callout and I'll add it to my list, but for the time being there is a sort of work around. If you added an image to your vault while it was open and haven't closed it, that image should be at the bottom of the list(I just sort things in order their cached right now, and things added this session get cached at the end). There is also a button in the filter area that looks like an up arrow and a down arrow and clicking that will reverse the order image are shown.

I will look into better long term sorting options though. Unsorted, added date, filename, and file size should all be pretty easy to implement and I can see use cases for each.

**Comment by FeralFlora** [comment]
> This is a solid callout and I'll add it to my list, but for the time being there is a sort of work around. If you added an image to your vault while it was open and haven't closed it, that image should be at the bottom of the list(I just sort things in order their cached right now, and things added this session get cached at the end). There is also a button in the filter area that looks like an up arrow and a down arrow and clicking that will reverse the order image are shown.
> 
> I will look into better long term sorting options though. Unsorted, added date, filename, and file size should all be pretty easy to implement and I can see use cases for each.

Great, looking forward to it, and thanks for the workaround in the meantime!
