### ISSUE TITLE
What is "related fields" ? How does it work?

### ISSUE THREAD

**Issue by wwjCMP** [TomNCatz/obsidian-gallery#18]
![Snipaste_2023-10-06_09-39-35](https://github.com/TomNCatz/obsidian-gallery/assets/32979859/4f6bfdf5-a23a-4195-a06a-b65ddf1bfc28)
As shown in the diagram, how are the image links in the "related fields" obtained?

**Comment by TomNCatz** [comment]
Files in the same folder with similar enough names.
Some example use cases:
- Page1.png, Page2.png, Page3.png
- MyGreatProject.png, MyGreatProject.blend, MyGreatProject.ksp

If you do not like this field it can be hidden in the hidden info section in settings. relatedFiles is what it is called and you can just mark it for hide.
This is a recently added feature, so I probably need to add documentation for it still.
