### ISSUE TITLE
Provide options for automatically opening and closing meta files

### ISSUE THREAD

**Issue by wwjCMP** [TomNCatz/obsidian-gallery#20]
Clicking on an image in the gallery  will automatically open the corresponding meta file in the sidebar. It would be great to provide an option to enable this feature.

**Comment by TomNCatz** [comment]
I'm not sure I understand, it already does this. Do you mean you want it to NOT do this?

**Comment by wwjCMP** [comment]
Yes, that’s what I mean. Currently it's default, I hope it's optional.

**Comment by TomNCatz** [comment]
That's interesting, Would you want to be able to turn it off permanently, or just temporarily? Does this seem more like a toggle button in the gallery itself or something to bury in the settings menu. 

I kind of consider the sidebar to be one of the most valuable aspects of the plugin, but I'll see what I can do.

**Comment by wwjCMP** [comment]
I believe providing a switch would be sufficient. Sometimes, when we are maintaining images, it would be better to have it automatically open. Sometimes, we just want to quickly find and browse specific images, and we may not be concerned with writing the image's metadata. Especially when I open three columns in Obsidian, I try to keep the sidebar closed; otherwise, my space becomes even smaller. I hope I have expressed my meaning clearly.

**Comment by wwjCMP** [comment]
I also found that in markdown files, images can be managed by directly adding tags to them using the right-click option. This way, there is no need to open the image information in the sidebar while invoking the right-click menu.

**Comment by TomNCatz** [comment]
There is already a toggle for opening the info panel while right clicking elsewhere in your notes. it is the 'Info panel anywhere' checkbox.

**Comment by wwjCMP** [comment]
> There is already a toggle for opening the info panel while right clicking elsewhere in your notes. it is the 'Info panel anywhere' checkbox.

I found that after adding tags to a image through the right-click menu, the info panel will open automatically, which conflicts with the previous idea. I hope that this automatic behavior will not be triggered when the sidebar is closed.
