### ISSUE TITLE
bug in version 1.6.2 😞 

### ISSUE THREAD

**Issue by 7Codez** [TomNCatz/obsidian-gallery#22]
why Images do not appear in the main gallery in version 1.6.2 ?
On Android 11 and Windows 10 devices

**Comment by TomNCatz** [comment]
This still works fine for me in windows 10. Was it working for you before 1.6.2? It is possible the changes I made to settings did not carry over properly for existing users. Does anything look funky in your settings window for the plugin?

**Comment by Cruisername** [comment]
I'm having the same issue with 1.6.2 and the newly released 1.6.3 on Win 11. Tried starting a fresh vault with default settings, but images still don't show. Earlier versions work fine.
