### ISSUE TITLE
Can't see "Main gallery default path" section

### ISSUE THREAD

**Issue by delunea** [TomNCatz/obsidian-gallery#24]
According to the screenshot on this github there should be a section of the settings right below "rebuild data cache" but I don't see such setting. Am I missing a toggle somewhere or is this a bug?

![image](https://github.com/TomNCatz/obsidian-gallery/assets/126142673/748e1b42-50bc-45b8-9208-7d53dbee6dd5)

**Comment by TomNCatz** [comment]
The image is just out of date. Honestly, I should just remove the image from the readme, it doesn't really add anything other than the ability to preview settings without installing the plugin. All of the descriptions are in the settings menu anyway
