### ISSUE TITLE
[FR] Copy Image links like Copy meta links in Context Menu

### ISSUE THREAD

**Issue by 7Codez** [TomNCatz/obsidian-gallery#26]
Please can add (Copy Image links) like (Copy meta links) in Context Menu.

**Comment by TomNCatz** [comment]
I think that exists here
![image](https://github.com/TomNCatz/obsidian-gallery/assets/33710598/5754ca51-0011-4340-a1ec-2238a72486d9)

is there a different result or context you want it under?

**Comment by TomNCatz** [comment]
Ah, did you mean when you right click on an embedded image outside the gallery?
