### ISSUE TITLE
[FR] Select images and add them in one file

### ISSUE THREAD

**Issue by 7Codez** [TomNCatz/obsidian-gallery#29]
Is it possible to select images and add all the selected images to one file?  Just like I do when selecting images, then tag them all at once.

**Comment by TomNCatz** [comment]
when you have multiple images selected the context menu has an option to copy image links. These are copied in the embeded format, so if you paste them into a note they should all embed in said note.

Alternatively you can put the names of the images into the 'name:' section of a gallery block separated by commas and as long as 'exclusive:' is not set to true it should list them all out. I've been thinking of adding a context menu option to expedite this.

**Comment by TomNCatz** [comment]
What do you mean by 'into a single file'? 
Do you mean you want those images to be moved to a new location on disc? The 'Move Images' option does this. 
Do you mean to have a single note that has a gallery with just those images in it? Cause that is the option I have been thinking about adding to the context menu that I described above.

**Comment by TomNCatz** [comment]
I don't think I'm going to implement the album like functionality you are describing as a hotkey. I am providing several ways to take a group of images in the gallery and copy paste them to a note. Further work on this kind of functionality just isn't in scope right now.
