### ISSUE TITLE
[BUG] printing to PDF shows loading gif instead of the image

### ISSUE THREAD

**Issue by naxey** [TomNCatz/obsidian-gallery#33]

**Comment by TomNCatz** [comment]
This plugin does not have a print to PDF feature, so I'm not sure what you're talking about. 

If you are using another tool to try and print the gallery, the gallery initially loads the images as a throbber to facilitate lazy loading. Whatever tool you are using to output the PDF would need to wait until the images have actually loaded in to pull the image data.
