### ISSUE TITLE
[bug] Some GIF images cannot be displayed in the image management interface

### ISSUE THREAD

**Issue by wwjCMP** [TomNCatz/obsidian-gallery#4]
Some GIF images cannot be displayed in the picture management interface, while others can. I can't find a pattern among them.

**Comment by TomNCatz** [comment]
Can't be displayed at all or don't play when displayed? And is this in the main gallery or block gallery? (for the most part they should be the same, but the active thumbs setting in the block gallery uses some svelte cod that I don't have as much control over)
If you have an example file that does not work(and you don't mind sharing it) it would help me to troubleshoot the issue.

**Comment by TomNCatz** [comment]
That's a bug alright. I probably messed up my regex somewhere. Thank you for the info!
